### ISSUE TITLE
MegaSAS.log

### ISSUE THREAD

**Issue by AlekseiPipl** [ArtemK007/Zabbix-LSI-RAID-Monitoring#2]
Hi there!
First of all, tnx for the script! It looks like it does it's job.

But I have a question.
The 'NoLog' command , does it really work on your side? Cauz my MegaSAS.log keep growing and growing, though there is a NoLog in the script you wrote.

Thanks!

**Comment by ArtemK007** [comment]
HI!

ye, it worked, at least 3 years ago :)
